version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: probot
    versions:
    - 11.1.0
    - 11.1.1
    - 11.2.1
    - 11.2.2
    - 11.2.3
    - 11.2.4
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
